### ISSUE TITLE
local_komettranslator does use curl instead of Moodle FileApi (lib/filelib.php)

### ISSUE THREAD

**Issue by GGeorggg** [center-for-learning-management/moodle-local_komettranslator#1]
Hallo @gtndevel @center-for-learning-management/think-modular @lassnj 

https://github.com/center-for-learning-management/moodle-local_komettranslator/blob/c6a35dc5f5d48e4dd3b2375791a017bd53ad67c5/classes/locallib.php#L181-L209

kann sich das jemand annehmen - hier wird Curl direkt aufgerufen anstelle die FileApi zu verwendet - das funktioniert aber nicht da curl in der Konfiguration nicht den Proxy verwendet.

Ähnlicher case wie bei https://github.com/center-for-learning-management/moodle-block_edupublisher/issues/54#event-7383665250

danke
Georg

**Comment by gtndevel** [comment]
Gefixed. Wer übernimmt das Deployment?

**Comment by GGeorggg** [comment]
Hallo @gschwed,

kannst du bitte die Fixes aus https://github.com/center-for-learning-management/moodle-local_komettranslator/commit/fc73145edfd883046934c243f51627031dd8d02c bitte in https://github.com/center-for-learning-management/eduvidual-src (main/test) branch übernehmen und pull request für branch prd anlegen (ich reviewe diesen sobald ich das am Testsystem getestet habe) und deploy am Produktivsystem.

danke
Georg

**Comment by lassnj** [comment]
wurde irgendwann mitdeployed.
