### ISSUE TITLE
neue Kompetenzraster kommen nicht an

### ISSUE THREAD

**Issue by lassnj** [center-for-learning-management/moodle-local_komettranslator#2]
Wenn der Sync von Komet-Translator angestoßen wird, werden bestehende aktive Kompetenzraster zwar aktualisiert (zumindest werden sie grün hinterlegt)
![grafik](https://github.com/center-for-learning-management/moodle-local_komettranslator/assets/22933650/8b483353-3da3-4cb0-b440-f81faae85af7)

aber neue kommen nicht dazu. Ein neues Kompetenzraster, das ankommen sollte ist z.B. 
Pflichtgegenstand Digitale-Grundbildung mit Übungen 2023 (AHS Unterstufe, Mittelschule) (Klasse: 5. - 8. Schulstufe)

Übersicht Kompetenzraster t4: https://t4.eduvidual.org/local/komettranslator/frameworks.php

**Comment by lassnj** [comment]
@ariepl FYI

**Comment by lassnj** [comment]
@prowebat bitte für Weihnachtsupdate 2023 einplanen. Danke!

**Comment by rschrenk** [comment]
Neue Raster müssen einmalig durch einen Admin bestätigt werden. Das ist kein Fehler sondern eine Qualitätssicherungsmaßnahme.

viele Raster beinhalteten ungültige Zeichen, die zwar im KOMET nicht sichtbar waren aber die Ansicht in Moodle gestört haben. Daher habe ich jeden Raster vor der ersten Freigabe kontrolliert.

**Comment by prowebat** [comment]
Hallo Robert,

Ah,  danke für die Info!

**Comment by lassnj** [comment]
"fehlendes Kompetenzraster" ist jetzt da. Ev. übersehen oder mittlerweile repariert...
